name: Fuzz Parser

on:
  push:
    paths:
      - common/scanner.h
  pull_request:
    paths:
      - common/scanner.h
  workflow_dispatch:

jobs:
  test:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vigoux/tree-sitter-fuzz-action@v1
        with:
          language: javascript
          external-scanner: javascript/src/scanner.c
          time: 60
